### PR TITLE
Swagger integration

### PR DESCRIPTION
**Pull request by amy-e-stone**
Swagger has now been integrated! 

Install the following dependency:
**pip install drf-yasg**

And you should be able to see the Swagger UI at:
http://127.0.0.1:8000/swagger/

### CODE REVIEW

**Comment by shanhix1-personal** [comment]
Looks amazing so far! Thanks so much for setting this up! 

Note to others: I had to use this link: http://localhost:8000/swagger/ 
And I had Django running while I ran `python -m pip install drf-yasg`, so I had to restart Django. 

A couple things: 
- (I can try this out & push a commit to this branch) I'd like to update the URLs & API calls so they show up in the swagger in more understandable sections: user, user data, and notification data
- Do you know why only the notification model is showing up, and not the user or userData models?
- Can we connect the URL to Heroku so people viewing the GitHub can view it without running it locally?

My view:
image
image
image

**Comment by amy-e-stone** [comment]
Yes we can view it in Heroku as well, I would like to merge the changes to main first before I push it to the server though, if that's ok with you. As for only the notification model showing up - I can look into it tomorrow.

**Comment by shanhix1-personal** [comment]
Yeah absolutely we can do the heroku stuff in a separate PR. And sounds good! I am noticing this too, duplicate URLs with different methods, which seem to mismatch:

image

**Comment by shanhix1-personal** [comment]
Alright @amy-e-stone, I fixed the issues & pushed a commit:
- Updated serializer references in the swagger_auto_schema
- Added descriptions to each API
- Updated URLs throughout the code base to use consist & standardized naming conventions. 

This is what it should look like now:
image
image
image
image

Approved for merge if you test it & everything still works ok for you. I went through the app and tested every screen/API call myself, but would be great to get another pair of eyes to make sure I didn't break anything.

**Pull request merged**
